### ISSUE TITLE
You get a warning while scaling controller nodes

### ISSUE THREAD

**Issue by OmkarDeshpande7** [platform9/vjailbreak#216]
### What steps did you take and what happened?

while scaling migration-controller-manager deployment, you get a warning

```
Warning: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key: node-role.kubernetes.io/master is use "node-role.kubernetes.io/control-plane" instead
```

The spec for the deployment looks like this.

```
    spec:                                                                                                                                                                       
      affinity:                                                                                                                                                                 
        nodeAffinity:                                                                                                                                                           
          requiredDuringSchedulingIgnoredDuringExecution:                                                                                                                       
            nodeSelectorTerms:                                                                                                                                                  
            - matchExpressions:                                                                                                                                                 
              - key: node-role.kubernetes.io/master                                                                                                                             
                operator: Exists 
```

### What did you expect to happen?

Should not get a warning

### Environment

v0.1.4

### vCenter version

any
